services:
  myapp:
    image: ghcr.io/asano69/myapp:latest
    container_name: myapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - myapp.env
    volumes:
      - ./data:/myapp/pb_data
        #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Europe/London
      #
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      #networks:
    #  - traefik_net
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.myapp.rule=Host(`myapp.app.internal`)
#volumes:
#  data:

#networks:
#  traefik_net:
#    external: true

